#! /usr/bin/env bash

# Shows the output of every command
set +x

pre_home() {
  echo "Creating config / cache directories..."

  # Polybar logs
  mkdir -p $HOME/.config/polybar/logs
  touch $HOME/.config/polybar/logs/bottom.log
  touch $HOME/.config/polybar/logs/top.log

  # FZF cache
  mkdir -p $HOME/.cache/fzf-hoogle
  touch $HOME/.cache/fzf-hoogle/cache.json

  # Desktop pic
  mkdir -p $HOME/Pictures/
  cp imgs/nixos.png $HOME/Pictures/

  # Nix daemon config for normal user
  mkdir -p $HOME/.config/nix
  cp home/daemon.conf $HOME/.config/nix/nix.conf
}

post_home() {
  # Set screenlock wallpaper
  echo "Setting screen-lock wallpaper"
  multilockscreen -u imgs/nix-wp.png
}

fresh_install() {
  ./switch system
  ./build pre-home
  ./switch home
  ./build post-home
}

case $1 in
  "fresh-install")
    fresh_install;;
  "pre-home")
    pre_home;;
  "post-home")
    post_home;;
  *)
    echo "Invalid option. Expected 'pre_home', 'post_home' or 'fresh-install'";;
esac
